Controllers/CalificacionesController.cs
using Actividad4LengProg3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Actividad4LengProg3.Controllers
{
    public class CalificacionesController : Controller
    {
        private readonly AppDbContext _context;

        public CalificacionesController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            ViewBag.Estudiantes = _context.Estudiantes
            .Select(e => new SelectListItem
            {
                Value = e.matriculaEstudiante,
                Text = e.matriculaEstudiante + " - " + e.nombreEstudiante + " - " + e.carreraEstudiante
            }).ToList();

            ViewBag.Materias = _context.Materias
            .Select(m => new SelectListItem
            {
                Value = m.codMateria,
                Text = m.codMateria + " - " + m.nombreMateria
            }).ToList();

            return View(new CalificacionViewModel());
        }


        [HttpPost]
        public IActionResult Calificar(CalificacionViewModel calificacion)
        {
            if (ModelState.IsValid)
            {
                _context.Calificaciones.Add(calificacion);
                _context.SaveChanges();
                TempData["Mensaje"] = "Estudiante calificado correctamente.";
                return RedirectToAction("Lista");
            }
            return View("Index", calificacion);
        }

        public IActionResult Lista()
        {
            var calificacion = _context.Calificaciones.ToList();
            return View(calificacion);
        }

        [HttpGet]
        public IActionResult Editar(string idcalificacion)
        {
            var calificacion = _context.Calificaciones.FirstOrDefault(c => c.idCalificacion.ToString() == idcalificacion);
            if (calificacion == null)
            {
                TempData["Mensaje"] = "No existe la nota indicada";
                return RedirectToAction("Lista");
            }
            return View(calificacion);
        }

        [HttpPost]
        public IActionResult Editar(CalificacionViewModel calificacion)
        {
            if (!ModelState.IsValid)
            {
                return View(calificacion);
            }
                var calificacionActual = _context.Calificaciones.FirstOrDefault(c => c.idCalificacion == calificacion.idCalificacion);
                if (calificacionActual == null)
                {
                    TempData["Mensaje"] = "No existe la calificación indicada.";
                    return RedirectToAction("Lista");
                }               
                
                calificacionActual.notaEstudiante = calificacion.notaEstudiante;
                
                _context.Update(calificacionActual);
                _context.SaveChanges();

                TempData["Mensaje"] = "La nota ha sido cambiada correctamente.";
                return RedirectToAction("Lista");            
        }

        public IActionResult Eliminar(int idcalificacion)
        {
            var calificacion = _context.Calificaciones.FirstOrDefault(c => c.idCalificacion == idcalificacion);
            if (calificacion != null)
            {
                _context.Calificaciones.Remove(calificacion);
                _context.SaveChanges();
                TempData["Mensaje"] = "La calificación ha sido eliminada correctamente.";
                return RedirectToAction("Lista");
            }
            return View(calificacion);
        }
    }
}

Controllers/EstudiantesController.cs
using Actividad4LengProg3.Models;
using Microsoft.AspNetCore.Mvc;
using System.Reflection;

namespace Actividad4LengProg3.Controllers
{
    public class EstudiantesController : Controller
    {
        private readonly AppDbContext _context;

        public EstudiantesController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Registrar(EstudianteViewModel estudiante)
        {
            if (ModelState.IsValid)
            {
                _context.Estudiantes.Add(estudiante);
                _context.SaveChanges();
                TempData["Mensaje"] = "Estudiante registrado satisfactoriamente.";
                return RedirectToAction("Lista");
            }   
            return View("Index", estudiante);
        }


        public IActionResult Lista()
        {

            var estudiantes = _context.Estudiantes.ToList();
            return View(estudiantes);

        }

        [HttpGet]
        public IActionResult Editar(string matricula)
        {
            var estudiante = _context.Estudiantes.FirstOrDefault(e => e.matriculaEstudiante == matricula);
            if (estudiante == null)
            {
                TempData["Mensaje"] = "No existe el estudiante indicado";
                return RedirectToAction("Lista");
            }
            return View(estudiante);
        }



        [HttpPost]
        public IActionResult Editar(EstudianteViewModel estudiante)
        {
            if (ModelState.IsValid)
            {
                var estudianteActual = _context.Estudiantes.FirstOrDefault(e => e.matriculaEstudiante == estudiante.matriculaEstudiante);

                if (estudianteActual == null)
                {
                    TempData["Mensaje"] = "No existe el estudiante indicado";
                    return RedirectToAction("Lista");
                }

                
                estudianteActual.nombreEstudiante = estudiante.nombreEstudiante;
                estudianteActual.carreraEstudiante = estudiante.carreraEstudiante;
                estudianteActual.correoEstudiante = estudiante.correoEstudiante;
                estudianteActual.telefonoEstudiante = estudiante.telefonoEstudiante;
                estudianteActual.fechaEstudiante = estudiante.fechaEstudiante;
                estudianteActual.generoEstudiante = estudiante.generoEstudiante;
                estudianteActual.turnoEstudiante = estudiante.turnoEstudiante;
                estudianteActual.ingresoEstudiante = estudiante.ingresoEstudiante;
                estudianteActual.porcentajebecaEstudiante = estudiante.porcentajebecaEstudiante;
                estudianteActual.becaEstudiante = estudiante.becaEstudiante;
                estudianteActual.tcEstudiante = estudiante.tcEstudiante;

                _context.Update(estudianteActual);
                _context.SaveChanges();    

                TempData["Mensaje"] = "Los datos del estudiante han sido actualizados correctamente.";
                return RedirectToAction("Lista");
            }

            return View(estudiante);
        }



        public IActionResult Eliminar(string matricula)
        {
            var estudiante = _context.Estudiantes.FirstOrDefault(e => e.matriculaEstudiante == matricula);
            if (estudiante != null) 
            {
                _context.Estudiantes.Remove(estudiante);
                _context.SaveChanges();
                TempData["Mensaje"] = "Estudiante eliminado satisfactoriamente.";
                return RedirectToAction("Lista");
            }
            return View(estudiante);
        }
    }
}

Controllers/MateriasController.cs
using Microsoft.AspNetCore.Mvc;
using Actividad4LengProg3.Models;

namespace Actividad4LengProg3.Controllers
{
    public class MateriasController : Controller
    {
        private readonly AppDbContext _context;

        public MateriasController(AppDbContext context) 
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Registrar(MateriaViewModel materia)
        {
            if(ModelState.IsValid)
            {
                _context.Materias.Add(materia);
                _context.SaveChanges();
                TempData["Mensaje"] = "Materia registrada satisfactoriamente.";
                return RedirectToAction("Lista");
            }
            return View("Index", materia);
        }
       
        public IActionResult Lista()
        {
            var materias = _context.Materias.ToList();
            return View(materias);
        }
        [HttpGet]
        public IActionResult Editar(string codmateria)
        {
            var materias = _context.Materias.FirstOrDefault(m => m.codMateria == codmateria);
            if(materias == null)
            {
                TempData["Mensaje"] = "No existe la materia indicada.";
                    return RedirectToAction("Lista");

            }

            return View(materias);
        }
        [HttpPost]
        public IActionResult Editar(MateriaViewModel materia)
        {
            if (ModelState.IsValid) {
                var materiaActual = _context.Materias.FirstOrDefault(m => m.codMateria == materia.codMateria);

                if (materiaActual == null)
                {
                    TempData["Mensaje"] = "No existe la materia indicada";
                    return RedirectToAction("Lista");
                }

                materiaActual.nombreMateria = materia.nombreMateria;
                materiaActual.creditoMateria = materia.creditoMateria;
                materiaActual.carreraMateria = materia.carreraMateria;

                _context.Update(materiaActual);
                _context.SaveChanges();

                TempData["Mensaje"] = "Los datos de la materia han sido editados correctamente.";
                return RedirectToAction("Lista");
            
            }
            return View(materia);
        }

        public IActionResult Eliminar(string codmateria)
        {
            var materia = _context.Materias.FirstOrDefault(m => m.codMateria == codmateria);
            if (materia != null)
            {
                _context.Materias.Remove(materia);
                _context.SaveChanges();
                TempData["Mensaje"] = "Materia eliminada satisfactoriamente.";
                return RedirectToAction("Lista");
            }
            return View(materia);
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Actividad4LengProg3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Actividad4LengProg3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Actividad4LengProg3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estudiantes" asp-action="Index">Registrar Estudiantes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Materias" asp-action="Index">Registrar Materias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calificaciones" asp-action="Index">Calificar Estudiantes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Actividad4LengProg3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>